Repository outerbase/starboard, pull requests merged in 2024-02, with the labels that each got.

#3 Default Plugin Support
  src/components/table/index.ts
  src/components/table/th.ts
  src/pages/index.astro
  src/types.ts
Labels: enhancement

#4 Support attributes
  src/components/table/index.ts
  src/components/table/td.ts
Labels: bug, enhancement

#8 dismiss plugin editor on outside click
  src/components/mutable-element.ts
  src/components/table/td.ts
Labels: bug
